# Generated by Django 5.2.8 on 2025-11-28 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('mrf', '0003_mrf_mrf_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('no_of_positions', models.PositiveIntegerField(default=1)),
                ('key_responsibility', models.TextField()),
                ('required_qualifications', models.TextField()),
                ('experience_range', models.CharField(max_length=50)),
                ('skills_competencies', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('in_progress', 'In Progress'), ('filled_internally', 'Filled Internally'), ('filled_by_consultancy', 'Filled by Consultancy'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('filled_by', models.CharField(blank=True, choices=[('internal', 'Internal'), ('consultancy', 'Consultancy')], max_length=20, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visible_to_consultancy', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_consultancy', models.ForeignKey(blank=True, limit_choices_to={'role': 'consultancy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='mrf.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='mrf.designation')),
                ('filled_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_filled', to=settings.AUTH_USER_MODEL)),
                ('mrf', models.OneToOneField(help_text='Related MRF that created this job', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='mrf.mrf')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('source', models.CharField(choices=[('internal', 'Internal HR'), ('consultancy', 'Consultancy')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('joined', 'Joined')], default='submitted', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=50)),
                ('expected_ctc', models.CharField(blank=True, max_length=50)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('assigned', 'Assigned to Consultancy'), ('reassigned', 'Reassigned to Another Consultancy'), ('unassigned', 'Unassigned from Consultancy'), ('filled_internal', 'Filled Internally'), ('filled_consultancy', 'Filled by Consultancy'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='jobs.job')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_assignment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['department'], name='jobs_departm_a3eb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_to_consultancy'], name='jobs_assigne_fc0817_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'candidate_email')},
        ),
    ]
