# Generated by Django 5.2.8 on 2025-12-01 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='filled_at',
            new_name='closed_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='filled_by_user',
        ),
        migrations.AddField(
            model_name='job',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, help_text='Detailed job description for public posting'),
        ),
        migrations.AddField(
            model_name='job',
            name='positions_filled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rating out of 5', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='jobassignmenthistory',
            name='new_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobassignmenthistory',
            name='old_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('in_progress', 'In Progress'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('internal_hr', 'Internal HR'), ('consultancy', 'Consultancy'), ('application_link', 'Application Link'), ('direct', 'Direct Application'), ('referral', 'Employee Referral')], default='direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('joined', 'Joined'), ('withdrawn', 'Withdrawn')], default='received', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Job Created'), ('assigned', 'Assigned to Consultancy'), ('reassigned', 'Reassigned to Another Consultancy'), ('unassigned', 'Unassigned from Consultancy'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('closed', 'Job Closed'), ('reopened', 'Job Reopened'), ('cancelled', 'Job Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='JobApplicationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('website', 'Company Website'), ('career_page', 'Career Page'), ('referral', 'Employee Referral'), ('email', 'Email'), ('other', 'Other')], max_length=50)),
                ('platform_name', models.CharField(blank=True, help_text='Custom platform name if "other" is selected', max_length=100)),
                ('unique_token', models.CharField(editable=False, help_text='Unique token for the application link', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Title for this link', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this link')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expiration date (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_links', to='jobs.job')),
            ],
            options={
                'db_table': 'job_application_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='application_link',
            field=models.ForeignKey(blank=True, help_text='Link through which candidate applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.jobapplicationlink'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='job_applica_status_6d1402_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['source'], name='job_applica_source_338df6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['application_link'], name='job_applica_applica_c61068_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationlink',
            index=models.Index(fields=['unique_token'], name='job_applica_unique__711027_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplicationlink',
            index=models.Index(fields=['job', 'platform'], name='job_applica_job_id_442f21_idx'),
        ),
    ]
