# Generated by Django 5.2.8 on 2025-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_filled_at_job_closed_at_remove_job_filled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=1, help_text='Candidate resume in any format', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
