# Generated by Django 5.2.8 on 2025-12-02 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0003_jobapplication_file_size_and_more'),
        ('mrf', '0003_mrf_mrf_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_internal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_internal_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned_internal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to_internal_hr',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['hr', 'hr_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_internal_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('in_progress', 'In Progress'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Job Created'), ('assigned', 'Assigned to Consultancy'), ('reassigned', 'Reassigned to Another Consultancy'), ('unassigned', 'Unassigned from Consultancy'), ('assigned_internal', 'Assigned to Internal HR'), ('reassigned_internal', 'Reassigned to Another Internal HR'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('closed', 'Job Closed'), ('reopened', 'Job Reopened'), ('cancelled', 'Job Cancelled')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_to_internal_hr'], name='jobs_assigne_7da88c_idx'),
        ),
    ]
