# Generated by Django 5.2.8 on 2025-12-02 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_assigned_internal_at_job_assigned_internal_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate_email', None), _negated=True), fields=('job', 'candidate_email'), name='unique_job_candidate_email_nonnull'),
        ),
    ]
