# Generated by Django 5.2.8 on 2025-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 0 to 100', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='relevant_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
