# Generated by Django 5.2.8 on 2025-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobapplication_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 0 to 100', max_digits=5, null=True),
        ),
    ]
