# Generated by Django 5.2.8 on 2025-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobapplication_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='availibility',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='current_employer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skill',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
