# Generated by Django 5.2.8 on 2025-12-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_report',
            field=models.FileField(blank=True, help_text='Candidate resume report.', null=True, upload_to='reports/'),
        ),
    ]
