# Generated by Django 5.2.8 on 2025-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_jobapplication_resume_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
