# Generated by Django 5.2.8 on 2025-12-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='technical_skills',
            field=models.TextField(default='pyhton,djnago,javascript'),
            preserve_default=False,
        ),
    ]
