# Generated by Django 5.2.8 on 2025-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('assigned_to_both', 'Assigned to Both'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
