# Generated by Django 5.2.8 on 2025-12-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_alter_job_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_job_candidate_email_nonnull',
        ),
    ]
