# Generated by Django 5.2.8 on 2025-12-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_jobapplication_unique_job_candidate_email_nonnull_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_job_nonnull',
        ),
    ]
