# Generated by Django 5.2.8 on 2025-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_jobapplication_unique_job_candidate_email_nonnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
