# Generated by Django 5.2.8 on 2025-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='work_from_office', max_length=50),
        ),
    ]
