# Generated by Django 5.2.8 on 2025-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('work_from_office', 'Work From Office'), ('work_from_home', 'Work From Home'), ('hybrid', 'Hybrid')], default='work_from_office', max_length=50),
        ),
    ]
