# Generated by Django 5.2.8 on 2025-12-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='slot_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
