# Generated by Django 5.2.8 on 2025-12-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_job_job_type'),
        ('jobs', '0022_jobapplication_slot_link'),
    ]

    operations = [
    ]
