# Generated by Django 5.2.8 on 2025-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_merge_20251216_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
