# Generated by Django 5.2.8 on 2025-12-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_jobapplication_candidate_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
