# Generated by Django 5.2.8 on 2025-12-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='referral_department',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_designation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_email',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_emp_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='referral_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
