# Generated by Django 5.2.8 on 2025-12-29 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_jobapplication_referral_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(help_text='Referral resume in any format', upload_to='referral_resumes/')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_name', models.CharField(blank=True, null=True)),
                ('referral_email', models.CharField(blank=True, null=True)),
                ('referral_emp_code', models.CharField(blank=True, null=True)),
                ('referral_designation', models.CharField(blank=True, null=True)),
                ('referral_department', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referral_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
