# Generated by Django 5.2.8 on 2025-12-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_referralapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralapplication',
            name='position_title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
