# Generated by Django 5.2.8 on 2026-01-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_referralapplication_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
