# Generated by Django 5.2.8 on 2026-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_jobapplication_is_shortlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('duplicate_rejected', 'Duplicate Rejected'), ('shortlisted', 'Shortlisted'), ('interview_pending_1', 'Interview 1 Pending'), ('interview_done_1', 'Interview 1 Completed'), ('interview_rejected_1', 'Rejected After Interview 1'), ('interview_next_2', 'Shortlisted For Round 2'), ('interview_pending_2', 'Interview 2 Pending'), ('interview_done_2', 'Interview 2 Completed'), ('interview_rejected_2', 'Rejected After Interview 2'), ('interview_next_3', 'Shortlisted For Round 3'), ('interview_pending_3', 'Interview 3 Pending'), ('interview_done_3', 'Interview 3 Completed'), ('interview_rejected_3', 'Rejected After Interview 3'), ('interview_next_final', 'Shortlisted For Round 3'), ('interview_pending_final', 'Interview 3 Pending'), ('interview_done_final', 'Final Round Of Interview Completed'), ('interview_rejected_final', 'Rejected After Interview 3'), ('interview_next_management_client', 'Shortlisted For Management / Client Interview'), ('interview_pending_management_client', 'Management / Client Interview Pending'), ('interview_done_management_client', 'Management / Client Interview Completed'), ('interview_rejected_management_client', 'Rejected After Management / Client Interview'), ('selected', 'Selected by Interview Panel'), ('approval_pending', 'Approval Pending (Sent to Hiring Manager)'), ('approved', 'Approved by Hiring Manager'), ('approval_rejected', 'Rejected During Approval'), ('salary_docs_pending', 'Salary Documents Pending'), ('salary_docs_uploaded', 'Salary Documents Uploaded'), ('hr_review_docs', 'HR Reviewing Salary Documents'), ('hr_review_ok', 'HR Review Completed'), ('hr_review_rejected', 'HR Rejected Salary Documents'), ('salary_annexure_prep', 'Salary Annexure Under Preparation'), ('salary_annexure_sent', 'Salary Annexure Sent to HR Head'), ('approved_annexure', 'Salary Annexure Approved'), ('rejected_annexure', 'Salary Annexure Rejected'), ('offer_pending', 'Offer Preparation Pending'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected by Candidate'), ('resignation_pending', 'Resignation Pending (Upload Required)'), ('resignation_uploaded', 'Resignation Uploaded'), ('resignation_review', 'Resignation Under Review'), ('resignation_approved', 'Resignation Approved'), ('resignation_rejected', 'Resignation Rejected'), ('docs_pending', 'Joining Documents Pending'), ('docs_uploaded', 'Joining Documents Uploaded'), ('review_docs', 'Document Review In Progress'), ('docs_approved', 'Documents Approved'), ('docs_incomplete', 'Documents Incomplete'), ('docs_unclear', 'Documents Unclear'), ('joining_pending', 'Joining Pending'), ('joining_poned', 'Joining Postponed'), ('joined', 'Joined'), ('rejected', 'Rejected')], default='received', max_length=50),
        ),
    ]
