# Generated by Django 5.2.8 on 2026-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0039_jobapplication_interview_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
