# Generated by Django 5.2.8 on 2026-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
