# Generated by Django 5.2.8 on 2026-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_jobapplication_feedback_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationlink',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='job_qrcodes/'),
        ),
    ]
