# Generated by Django 5.2.8 on 2026-02-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_jobapplicationlink_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='referral_phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='referral_phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
