# Generated by Django 5.2.8 on 2026-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_jobapplication_referral_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('internal_hr', 'Internal HR'), ('consultancy', 'Consultancy'), ('application_link', 'Application Link'), ('direct', 'Direct Application'), ('referral', 'Employee Referral'), ('career_page', 'Career Page')], default='direct', max_length=50),
        ),
    ]
