# Generated by Django 5.2.8 on 2026-03-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_alter_jobapplication_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='inperson_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
