# Generated by Django 5.2.8 on 2026-03-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_jobapplication_inperson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
