# Generated by Django 5.2.8 on 2026-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0048_alter_jobapplication_current_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('internal_hr', 'Internal HR'), ('consultancy', 'Consultancy'), ('application_link', 'Application Link'), ('direct', 'Direct Application'), ('referral', 'Employee Referral'), ('career_page', 'Career Page'), ('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed')], default='direct', max_length=50),
        ),
    ]
