# Generated by Django 5.2.8 on 2026-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_alter_jobapplication_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationlink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('website', 'Company Website'), ('career_page', 'Career Page'), ('referral', 'Employee Referral'), ('email', 'Email'), ('other', 'Other'), ('consultancy', 'Consultancy')], max_length=50),
        ),
    ]
