# Generated by Django 5.2.8 on 2026-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_alter_jobapplicationlink_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
