# Generated by Django 5.2.8 on 2026-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_dashboard_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
