# Generated by Django 5.2.8 on 2026-03-16 08:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_alter_jobapplication_candidate_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(help_text='Career Page resume in any format', upload_to='career_resumes/')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'career_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndeedApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(help_text='Indeed resume in any format', upload_to='indeed_resumes/')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indeed_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkedInApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(help_text='LinkedIn resume in any format', upload_to='linkedin_resumes/')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linkedin_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NaukriApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(help_text='Naukri resume in any format', upload_to='naukri_resumes/')),
                ('original_filename', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_title', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naukri_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
