# Generated by Django 5.2.8 on 2026-03-17 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0053_careerapplication_indeedapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('career_page', 'Career Page'), ('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed')], max_length=20)),
                ('resume', models.FileField(upload_to='applications/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('position_title', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CareerApplication',
        ),
        migrations.DeleteModel(
            name='IndeedApplication',
        ),
        migrations.DeleteModel(
            name='LinkedInApplication',
        ),
        migrations.DeleteModel(
            name='NaukriApplication',
        ),
    ]
