# Generated by Django 5.2.8 on 2026-03-18 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_application_delete_careerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_consultancies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'consultancy'}, null=True, related_name='consultancy_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_internal_hrs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['hr', 'hr_manager', 'admin']}, null=True, related_name='internal_hr_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='round_name',
            field=models.CharField(blank=True, choices=[('hr_round', 'HR Round'), ('technical_round', 'Technical Round'), ('case_study_round', 'Case Study Round'), ('final_round', 'Final Round'), ('management_client_round', 'Management / Client Round')], null=True),
        ),
    ]
