# Generated by Django 5.2.8 on 2026-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_application_availibility_application_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
