# Generated by Django 5.2.8 on 2026-03-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_application_candidate_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_applications', to='jobs.job'),
        ),
    ]
