# Generated by Django 5.2.8 on 2026-03-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0058_application_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_id',
            new_name='job',
        ),
    ]
