# Generated by Django 5.2.8 on 2026-03-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_rename_job_id_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
