# Generated by Django 5.2.8 on 2026-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_jobapplication_interview_end_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='held_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when put on hold', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason for holding the job'),
        ),
        migrations.AddField(
            model_name='job',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('assigned_to_both', 'Assigned to Both'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], help_text='Status before being put on hold (for restoration)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('assigned_to_both', 'Assigned to Both'), ('on_hold', 'On Hold'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
    ]
