# Generated by Django 5.2.8 on 2026-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_application_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='offer_decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
