# Generated by Django 5.2.8 on 2026-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0064_jobapplication_offer_decline_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('assigned_to_both', 'Assigned to Both'), ('joining_pending', 'Joining Pending'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], help_text='Status before being put on hold (for restoration)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned_to_consultancy', 'Assigned to Consultancy'), ('assigned_to_internal_hr', 'Assigned to Internal HR'), ('assigned_to_both', 'Assigned to Both'), ('on_hold', 'On Hold'), ('joining_pending', 'Joining Pending'), ('filled', 'Position Filled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Job Created'), ('assigned', 'Assigned to Consultancy'), ('reassigned', 'Reassigned to Another Consultancy'), ('unassigned', 'Unassigned from Consultancy'), ('assigned_internal', 'Assigned to Internal HR'), ('reassigned_internal', 'Reassigned to Another Internal HR'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('closed', 'Job Closed'), ('filled', 'Position Filled'), ('reopened', 'Job Reopened'), ('cancelled', 'Job Cancelled')], max_length=50),
        ),
    ]
