# Generated by Django 5.2.8 on 2026-05-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0066_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='offer_accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
