# Generated by Django 5.2.8 on 2026-05-07 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_jobapplication_offer_accepted_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, this job is only visible to authorized users'),
        ),
        migrations.AddField(
            model_name='job',
            name='selected_viewers',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this private job', related_name='viewable_private_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
