# Generated by Django 5.2.8 on 2026-05-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_job_is_private_job_selected_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('internal_hr', 'Internal HR'), ('consultancy', 'Consultancy'), ('application_link', 'Application Link'), ('direct', 'Direct Application'), ('referral', 'Employee Referral'), ('career_page', 'Career Page'), ('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('campus_drive', 'Campus Drive')], default='direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplicationlink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('website', 'Company Website'), ('career_page', 'Career Page'), ('referral', 'Employee Referral'), ('email', 'Email'), ('other', 'Other'), ('direct', 'Direct Application'), ('campus_drive', 'Campus Drive'), ('internal_hr', 'Internal HR'), ('consultancy', 'Consultancy')], max_length=50),
        ),
    ]
