# Generated by Django 5.2.8 on 2026-05-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0069_alter_jobapplication_source_and_more'),
        ('mrf', '0034_mrf_is_private_mrf_selected_viewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrf.department'),
        ),
        migrations.AddField(
            model_name='application',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrf.designation'),
        ),
    ]
