# Generated by Django 5.2.8 on 2026-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_application_is_touched_application_touched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralapplication',
            name='is_touched',
            field=models.BooleanField(default=False, help_text='Has the candidate been touched at least once?'),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='touched_at',
            field=models.DateTimeField(blank=True, help_text='When was the candidate last touched?', null=True),
        ),
    ]
