# Generated by Django 5.2.8 on 2026-06-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0075_alter_jobapplication_bgv_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
