# Generated by Django 5.2.8 on 2026-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0076_alter_jobapplication_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the platform application active?'),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the referral application active?'),
        ),
        migrations.AlterField(
            model_name='jobassignmenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Job Created'), ('assigned', 'Assigned to Consultancy'), ('reassigned', 'Reassigned to Another Consultancy'), ('unassigned', 'Unassigned from Consultancy'), ('assigned_internal', 'Assigned to Internal HR'), ('reassigned_internal', 'Reassigned to Another Internal HR'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('closed', 'Job Closed'), ('filled', 'Position Filled'), ('reopened', 'Job Reopened'), ('cancelled', 'Job Cancelled'), ('hold', 'Job Put on Hold'), ('hold_released', 'Job Hold Released'), ('deleted', 'Job Soft Deleted')], max_length=50),
        ),
    ]
