# Generated by Django 5.2.8 on 2026-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_alter_jobassignmenthistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the application active?'),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the referral application active?'),
        ),
    ]
