# Generated by Django 5.2.8 on 2026-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0078_jobapplication_cultural_buddy_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_hod_survey_filled',
            field=models.BooleanField(default=False),
        ),
    ]
