# Generated by Django 5.2.8 on 2026-08-04 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0079_jobapplication_is_hod_survey_filled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['match_score', 'status', 'created_at'], name='job_applica_match_s_055869_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['candidate_name', 'candidate_email'], name='job_applica_candida_c83694_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job_id', 'is_active'], name='job_applica_job_id_2f26e3_idx'),
        ),
    ]
