# Generated by Django 5.2.8 on 2026-08-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0080_jobapplication_job_applica_match_s_055869_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_d90_survey_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='it_ticket_closed',
            field=models.BooleanField(default=False),
        ),
    ]
