# Generated by Django 5.2.8 on 2026-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0081_add_d90_survey_sent_and_it_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_d90_survey_filled',
            field=models.BooleanField(default=False),
        ),
    ]
