# Generated by Django 5.2.8 on 2026-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0082_d90_candidate_survey_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_d30_survey_sent',
            field=models.BooleanField(default=False),
        ),
    ]
