# Generated by Django 5.2.8 on 2026-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0084_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_esign_packet_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_esign_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
