# Generated by Django 5.2.8 on 2026-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0085_add_esign_guard_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_minus_15_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_minus_2_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_minus_7_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
