# Generated by Django 5.2.8 on 2026-08-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0086_jobapplication_is_doj_minus_15_triggered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_0_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_45_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_doj_7_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
