# Generated by Django 5.2.8 on 2026-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0087_jobapplication_is_doj_0_triggered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='d45_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='d90_reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_d45_call_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_d90_call_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
