# Generated by Django 5.2.8 on 2026-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0088_jobapplication_d45_reminder_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_d5_verification_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_d5_verification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
