# Generated by Django 5.1.1 on 2026-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0090_add_terminated_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_undertaking_signoff_sent',
            field=models.BooleanField(default=False),
        ),
    ]
