# Generated by Django 5.2.8 on 2026-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0091_jobapplication_is_undertaking_signoff_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_undertaking_signoff_completed',
            field=models.BooleanField(default=False),
        ),
    ]
