# Generated by Django 5.2.8 on 2026-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0092_jobapplication_is_undertaking_signoff_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='revert_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
