# Generated by Django 5.2.8 on 2026-09-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0093_application_revert_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='crafter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
