# Generated by Django 5.1.1 on 2026-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0095_jobapplication_bgv_termination_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_tagged',
            field=models.BooleanField(default=False, help_text='Tagged application without job (department and designation only)'),
        ),
    ]
