# Generated by Django 5.2.8 on 2026-10-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0098_jobapplication_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
