# Generated by Django 5.2.8 on 2025-12-19 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_alter_jobapplication_candidate_history'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_round', models.CharField(blank=True, choices=[('round_1', 'Round 1'), ('round_2', 'Round 2'), ('final', 'Final Round')], max_length=50, null=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='jobs.jobapplication')),
            ],
        ),
    ]
