# Generated by Django 5.2.8 on 2025-12-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_interviewfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview_round',
            field=models.CharField(blank=True, choices=[('hr_round', 'HR Round'), ('technical_round_1', 'Technical Round 1'), ('technical_round_2', 'Technical Round 2'), ('final_round', 'Final Round')], max_length=50, null=True),
        ),
    ]
