# Generated by Django 5.2.8 on 2026-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_alter_interviewfeedback_interview_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='analytical_thinking_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='attitude_intent_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='behavioral',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='behavioral_cultural_fit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='bond',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='communication_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='cultural_fit_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='current_ctc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='current_organization',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='department',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='designation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='expected_ctc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='hometown',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interviewer_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='job_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='notice_period',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='personal_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='preferred_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='problem_solving_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='role_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='stability_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='team_handling_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='technical_skill_rating',
            field=models.IntegerField(default=0),
        ),
    ]
