# Generated by Django 5.2.8 on 2026-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_remove_interviewfeedback_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='current_organization_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='analytical_thinking_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='attitude_intent_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='communication_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='cultural_fit_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='problem_solving_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='stability_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='team_handling_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='technical_skill_rating',
            field=models.FloatField(default=0),
        ),
    ]
