# Generated by Django 5.2.8 on 2026-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_interviewfeedback_current_organization_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='analytical_thinking_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='attitude_intent_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='communication_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='cultural_fit_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='problem_solving_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='stability_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='team_handling_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='technical_skill_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
