# Generated by Django 5.2.8 on 2026-01-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_interviewfeedback_analytical_thinking_rating_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='achievement_orientation_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='areas_of_improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='business_acumen_industry_understanding_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='business_acumen_industry_understanding_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='competency_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='competency_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='current_designation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='current_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='goals_development_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interpersonal_skills_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='interpersonal_skills_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='leadership_skills_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='leadership_skills_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='learning_agility_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='learning_agility_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='motivation_for_change_career_aspirations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='ownership_accountibility_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='ownership_accountibility_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='problem_solving_critical_thinking_decision_making_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='problem_solving_critical_thinking_decision_making_rating_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='satbility_reliability_commitment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='strength_areas_of_improvement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='work_mode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
