# Generated by Django 5.2.8 on 2026-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_interviewfeedback_achievement_orientation_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview_round',
            field=models.CharField(blank=True, choices=[('hr_round', 'HR Round'), ('technical_round_1', 'Technical Round 1'), ('technical_round_2', 'Technical Round 2'), ('final_round', 'Final Round'), ('management_client_round', 'Management / Client Round')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='is_selected',
            field=models.CharField(blank=True, choices=[('hire', 'Hire'), ('strong_hire', 'Strong Hire'), ('reject', 'Reject')], default='reject', null=True),
        ),
    ]
