# Generated by Django 5.2.8 on 2026-01-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0008_alter_interviewfeedback_interview_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview_round',
            field=models.CharField(blank=True, choices=[('hr_round', 'HR Round'), ('technical_round', 'Technical Round'), ('case_study_round', 'Case Study Round'), ('final_round', 'Final Round'), ('management_client_round', 'Management / Client Round')], max_length=50, null=True),
        ),
    ]
