# Generated by Django 5.2.8 on 2026-01-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_alter_interviewfeedback_interview_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='case_study_round_avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='final_round_avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='hr_round_avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='management_client_round_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='tech_round_avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
