# Generated by Django 5.2.8 on 2026-02-10 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_magiclink_company'),
        ('slots', '0010_interviewfeedback_case_study_round_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewer',
            options={'ordering': ['email']},
        ),
        migrations.AddField(
            model_name='interviewer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='interviewer',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uniq_interviewer_email_per_company'),
        ),
    ]
