# Generated by Django 5.2.8 on 2026-02-26 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_magiclink_company'),
        ('slots', '0011_alter_interviewer_options_interviewer_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
