# Generated by Django 5.2.8 on 2026-02-26 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_magiclink_company'),
        ('slots', '0012_interviewlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewlocation',
            name='address',
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='address_line_1',
            field=models.CharField(default='14th Floor, 1410, West Wing,Venus Stratum, Jhansi Ki Rani,B/H GSRTC Bus Stop, Nehrunagar', max_length=255),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='pincode',
            field=models.CharField(default='380015', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewlocation',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewlocation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_locations', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='interviewlocation',
            name='name',
            field=models.CharField(default='Knowcraft', max_length=255),
        ),
    ]
