# Generated by Django 5.2.8 on 2026-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0013_remove_interviewlocation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
