# Generated by Django 5.2.8 on 2026-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0015_interviewlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewlocation',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
