# Generated by Django 5.2.8 on 2026-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0016_interviewlocation_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
