# Generated by Django 5.2.8 on 2026-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0018_alter_interviewfeedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the interviewer active?'),
        ),
    ]
