# Generated by Django 5.2.8 on 2026-05-27 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_company_created_at_alter_magiclink_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('path', models.TextField(help_text='Full request path')),
                ('endpoint_name', models.CharField(blank=True, default='', help_text='DRF view name if available', max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('query_params', models.TextField(blank=True, default='', help_text='Query string parameters')),
                ('request_body', models.TextField(blank=True, default='', help_text='Sanitized request body (passwords removed)')),
                ('response_summary', models.TextField(blank=True, default='', help_text='Short summary of the response')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('target_model', models.CharField(blank=True, default='', help_text="e.g. 'jobs.JobApplication'", max_length=255)),
                ('target_id', models.CharField(blank=True, default='', help_text='PK of the affected object', max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('flushed_to_blob', models.BooleanField(db_index=True, default=False, help_text='Whether this log has been written to a blob file.')),
                ('company', models.ForeignKey(blank=True, help_text='Company the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. NULL if anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='auditlog_au_user_id_61cdd8_idx'), models.Index(fields=['company', 'timestamp'], name='auditlog_au_company_649b3f_idx'), models.Index(fields=['action', 'timestamp'], name='auditlog_au_action_c6fc70_idx'), models.Index(fields=['flushed_to_blob', 'timestamp'], name='auditlog_au_flushed_99e597_idx')],
            },
        ),
    ]
