# Generated by Django 5.2.8 on 2026-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Client IP address (IPv4, IPv6, or with port if proxy adds it)', max_length=45, null=True),
        ),
    ]
