# Generated by Django 5.2.8 on 2026-05-11 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0069_alter_jobapplication_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateBGV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ongrid_individual_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('insufficient', 'Insufficient'), ('failed', 'Failed')], default='initiated', max_length=50)),
                ('report_url', models.URLField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bgv', to='jobs.jobapplication')),
            ],
        ),
    ]
