# Generated by Django 5.2.8 on 2026-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebgv',
            name='bgv_scheduled_date',
            field=models.DateField(blank=True, help_text='Date when BGV should be triggered (15 days before joining for experienced candidates)', null=True),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='is_fresher',
            field=models.BooleanField(default=True, help_text='True if candidate has < 1 year experience'),
        ),
        migrations.AlterField(
            model_name='candidatebgv',
            name='status',
            field=models.CharField(choices=[('pending_schedule', 'Pending Schedule'), ('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('insufficient', 'Insufficient'), ('failed', 'Failed')], default='pending_schedule', max_length=50),
        ),
    ]
