# Generated by Django 5.2.8 on 2026-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv', '0003_alter_candidatebgv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebgv',
            name='ongrid_status',
            field=models.JSONField(blank=True, default=dict, help_text='Latest status payload fetched from OnGrid ongrid-status endpoint'),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='raw_initiation_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw request payload sent to OnGrid during the last initiation attempt'),
        ),
    ]
