# Generated by Django 5.2.8 on 2026-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv', '0004_candidatebgv_ongrid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebgv',
            name='av_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='bav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='cc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ccrv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='cvv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='dlv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='drg_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='eduv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='efirc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ehc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='empv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='eref_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='fmc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='gdc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='iaf_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='icav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ipav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ladv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='lapv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='lav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='nsorc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ofacc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='padv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='panv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='papv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='pav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='pcc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='ppv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='prc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='pvlf_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='smc_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='vidv_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
        migrations.AddField(
            model_name='candidatebgv',
            name='xav_status',
            field=models.CharField(blank=True, default='NOT_REQUESTED', max_length=50),
        ),
    ]
