# Generated by Django 5.2.8 on 2026-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgv', '0005_candidatebgv_av_status_candidatebgv_bav_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebgv',
            name='status',
            field=models.CharField(choices=[('pending_schedule', 'Pending Schedule'), ('initiated', 'BGV Initiated'), ('pending', 'Pending Verification'), ('on_hold', 'On Hold'), ('in_progress', 'BGV In Progress'), ('under_review', 'Under Review'), ('insufficiency_raised', 'Insufficiency Raised'), ('data_insufficient', 'Data Insufficient'), ('awaiting_candidate_input', 'Awaiting Candidate Input'), ('awaiting_employer_response', 'Awaiting Employer Response'), ('awaiting_university_response', 'Awaiting University Response'), ('awaiting_court_response', 'Awaiting Court Response'), ('clear', 'BGV Clear'), ('completed', 'BGV Completed'), ('closed', 'BGV Closed'), ('verified', 'Verified'), ('unable_to_verify', 'Unable To Verify'), ('discrepancy', 'Discrepancy Found'), ('failed', 'BGV Failed'), ('cancelled', 'BGV Cancelled'), ('rejected', 'BGV Rejected'), ('expired', 'BGV Expired')], default='pending_schedule', max_length=50),
        ),
    ]
