# Generated by Django 5.2.8 on 2026-03-11 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_department'),
        ('jobs', '0051_dashboard_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExperienceFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('feedback_type', models.CharField(choices=[('rejection', 'Rejection Feedback'), ('offer', 'Offer Feedback')], max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating out of 5', null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_feedbacks', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'candidate_experience_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultancy_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ads_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee_package', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_costs', to='accounts.company')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_cost', to='jobs.job')),
            ],
            options={
                'db_table': 'recruitment_costs',
                'ordering': ['-created_at'],
            },
        ),
    ]
