# Generated by Django 5.2.8 on 2026-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_dashboard_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateexperiencefeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='candidateexperiencefeedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='better_handling',
            field=models.TextField(blank=True, help_text='Was there any moment that could have been handled better? (min 15 words)'),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='communication',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Satisfied'), (4, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='improvement_suggestion',
            field=models.TextField(blank=True, help_text='What is one thing we could improve in our recruitment process? (min 15 words)'),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='interviewer_quality',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='most_frustrating',
            field=models.TextField(blank=True, help_text='What was the most frustrating part of our recruitment process? (min 15 words)'),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='nps_score',
            field=models.PositiveIntegerField(blank=True, help_text='0 = Not at all likely, 10 = Extremely likely', null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='overall_satisfaction',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Satisfied'), (4, 'Very Satisfied')], null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='process_ease',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very Difficult'), (2, 'Difficult'), (3, 'Easy'), (4, 'Very Easy')], null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='recruitment_speed',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Very Slow'), (2, 'Slow'), (3, 'Acceptable'), (4, 'Fast'), (5, 'Very Fast')], null=True),
        ),
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='stage_reached',
            field=models.CharField(blank=True, choices=[('application', 'Application Stage'), ('hr_interview', 'HR Interview'), ('technical_interview', 'Technical Interview'), ('final_interview', 'Final Interview'), ('offer', 'Offer Stage')], max_length=30),
        ),
    ]
