# Generated by Django 5.2.8 on 2026-04-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_candidate_survey_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='stage_reached',
            field=models.CharField(blank=True, choices=[('application', 'Application Stage'), ('hr_round', 'HR Round'), ('technical_round', 'Technical Round'), ('case_study_round', 'Case Study Round'), ('final_round', 'Final Round'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('management_client_round', 'Management Client Round')], max_length=30),
        ),
    ]
