# Generated by Django 5.2.8 on 2026-04-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_candidateexperiencefeedback_stage_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='feedback_type',
            field=models.CharField(choices=[('rejection', 'Rejection Feedback'), ('offer', 'Offer Feedback')], max_length=50),
        ),
    ]
