# Generated by Django 5.2.8 on 2026-04-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_candidateexperiencefeedback_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='communication',
            field=models.CharField(blank=True, choices=[('very_dissatisfied', 'Very Dissatisfied'), ('dissatisfied', 'Dissatisfied'), ('satisfied', 'Satisfied'), ('very_satisfied', 'Very Satisfied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='interviewer_quality',
            field=models.CharField(blank=True, choices=[('very_poor', 'Very Poor'), ('poor', 'Poor'), ('average', 'Average'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='overall_satisfaction',
            field=models.CharField(blank=True, choices=[('very_dissatisfied', 'Very Dissatisfied'), ('dissatisfied', 'Dissatisfied'), ('satisfied', 'Satisfied'), ('very_satisfied', 'Very Satisfied')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='process_ease',
            field=models.CharField(blank=True, choices=[('very_difficult', 'Very Difficult'), ('difficult', 'Difficult'), ('easy', 'Easy'), ('very_easy', 'Very Easy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='recruitment_speed',
            field=models.CharField(blank=True, choices=[('very_slow', 'Very Slow'), ('slow', 'Slow'), ('acceptable', 'Acceptable'), ('fast', 'Fast'), ('very_fast', 'Very Fast')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexperiencefeedback',
            name='stage_reached',
            field=models.CharField(blank=True, choices=[('application', 'Application Stage'), ('hr_round', 'HR Round'), ('technical_round', 'Technical Round'), ('case_study_round', 'Case Study Round'), ('final_round', 'Final Round'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('management_client_round', 'Management Client Round'), ('approval_rejected', 'Approval Rejected'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
