# Generated by Django 5.1.1 on 2026-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_candidateexperiencefeedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexperiencefeedback',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
