# Generated by Django 5.2.8 on 2026-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('hr', 'HR'), ('department_head', 'Department Head'), ('consultancy', 'Consultancy')], max_length=20, null=True),
        ),
    ]
