# Generated by Django 5.2.8 on 2026-02-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_roles_delete_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company'], name='accounts_us_company_7b39c2_idx'),
        ),
    ]
