# Generated by Django 5.2.8 on 2026-02-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_magiclink_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magiclink',
            name='company',
        ),
    ]
