# Generated by Django 5.2.8 on 2026-02-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='interview_type',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
