# Generated by Django 5.2.8 on 2025-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meeting_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
