# Generated by Django 5.2.8 on 2026-02-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_interview_type_booking_location'),
        ('jobs', '0044_jobapplicationlink_qr_code'),
        ('slots', '0012_interviewlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.interviewlocation'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start'], name='booking_boo_start_5c9077_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['interviewer'], name='booking_boo_intervi_13c455_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['location'], name='booking_boo_locatio_04a5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['interview_type'], name='booking_boo_intervi_7046d6_idx'),
        ),
    ]
