# Generated by Django 5.2.8 on 2026-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=50)),
                ('subscription_id', models.CharField(max_length=255)),
                ('resource', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event_id', 'change_type', 'subscription_id')},
            },
        ),
    ]
