# Generated by Django 5.2.8 on 2026-03-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_grapheventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
