# Generated by Django 5.2.8 on 2026-03-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_systemlock'),
        ('slots', '0017_interviewer_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='slots.interviewer'),
        ),
    ]
