# Generated by Django 5.2.8 on 2025-11-26 05:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'MRF Approval Workflow'", max_length=255)),
                ('level', models.IntegerField(help_text='Approval level (1, 2, 3, etc.)')),
                ('required_role', models.CharField(help_text='Role required for this level', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(help_text='Order of execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'level'],
                'unique_together': {('name', 'level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MRF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_request', models.DateField(default=django.utils.timezone.now)),
                ('requested_by_name', models.CharField(max_length=255)),
                ('requested_by_designation', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('no_of_vacancies', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(choices=[('ahmedabad', 'Ahmedabad'), ('mumbai', 'Mumbai'), ('delhi', 'Delhi'), ('bangalore', 'Bangalore')], default='ahmedabad', max_length=50)),
                ('resigned_crafter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resigned_crafter_ecode', models.CharField(blank=True, max_length=100, null=True)),
                ('key_responsibility', models.TextField()),
                ('required_qualifications', models.TextField()),
                ('experience_range', models.CharField(help_text="e.g., '2-5 years'", max_length=100)),
                ('skills_competencies', models.TextField()),
                ('business_justification', models.TextField()),
                ('salary_range', models.CharField(help_text="e.g., '5-8 LPA'", max_length=100)),
                ('expected_date_of_joining', models.DateField()),
                ('case_study_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=10)),
                ('technical_interview_1', models.CharField(help_text='Name of interviewer', max_length=255)),
                ('technical_interview_2', models.CharField(blank=True, help_text='Optional', max_length=255, null=True)),
                ('final_interview', models.CharField(help_text='Name of final interviewer', max_length=255)),
                ('requisition_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=30)),
                ('current_approval_level', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrfs', to='mrf.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrfs', to='mrf.designation')),
                ('position_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_mrfs', to='mrf.department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrfs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MRF',
                'verbose_name_plural': 'MRFs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRFApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrf_approvals', to=settings.AUTH_USER_MODEL)),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mrf.mrf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRFRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_notes', models.TextField()),
                ('previous_data', models.JSONField(help_text='Store previous MRF data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='mrf.mrf')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
