# Generated by Django 5.2.8 on 2025-11-27 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'HR First Workflow', 'Admin First Workflow'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of this workflow')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to disable this workflow')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as default for new MRFs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='approvalworkflow',
            options={'ordering': ['template', 'order', 'level']},
        ),
        migrations.AlterField(
            model_name='mrf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('pending_level_3', 'Pending Level 3 Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mrf.workflowtemplate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrf',
            name='workflow_template',
            field=models.ForeignKey(default=0, help_text='The workflow template this MRF follows', on_delete=django.db.models.deletion.PROTECT, related_name='mrfs', to='mrf.workflowtemplate'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('template', 'level')},
        ),
        migrations.RemoveField(
            model_name='approvalworkflow',
            name='name',
        ),
    ]
