# Generated by Django 5.2.8 on 2025-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0002_workflowtemplate_alter_approvalworkflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='mrf_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
