# Generated by Django 5.2.8 on 2025-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0003_mrf_mrf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='location',
            field=models.CharField(default='ahmedabad', max_length=50),
        ),
    ]
