# Generated by Django 5.2.8 on 2025-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0004_alter_mrf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='interviewer_email_1',
            field=models.EmailField(default='knowkrafthrms@gmail.com', help_text='Email of interviewer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mrf',
            name='interviewer_email_2',
            field=models.EmailField(blank=True, help_text='Optional', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrf',
            name='interviewer_email_final',
            field=models.EmailField(default='shahanand1072004@gmail.com', help_text='Email of final interviewer', max_length=50),
            preserve_default=False,
        ),
    ]
