# Generated by Django 5.2.8 on 2025-12-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0005_mrf_interviewer_email_1_mrf_interviewer_email_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='final_interview',
            field=models.CharField(blank=True, help_text='Name of final interviewer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='technical_interview_1',
            field=models.CharField(blank=True, help_text='Name of interviewer', max_length=255, null=True),
        ),
    ]
