# Generated by Django 5.2.8 on 2025-12-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0006_alter_mrf_final_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='location',
            field=models.CharField(default='ahmedabad', max_length=255),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
