# Generated by Django 5.2.8 on 2025-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0007_alter_mrf_location_alter_mrf_requisition_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='interviewer_email_final',
            field=models.EmailField(blank=True, help_text='Email of final interviewer', max_length=50, null=True),
        ),
    ]
