# Generated by Django 5.2.8 on 2025-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0008_alter_mrf_interviewer_email_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='job_type',
            field=models.CharField(choices=[('work_from_office', 'Work From Office'), ('work_from_home', 'Work From Home'), ('hybrid', 'Hybrid')], default='work_from_office', max_length=50),
        ),
    ]
