# Generated by Django 5.2.8 on 2025-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0009_mrf_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='resigned_crafter_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
