# Generated by Django 5.2.8 on 2025-12-17 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0010_mrf_resigned_crafter_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedJoiningDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_joining', to='mrf.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_joining', to='mrf.designation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
