# Generated by Django 5.2.8 on 2025-12-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0011_expectedjoiningdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedjoiningdate',
            name='department',
        ),
    ]
