# Generated by Django 5.2.8 on 2025-12-18 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0012_remove_expectedjoiningdate_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='approver',
            field=models.ForeignKey(default='a7408c6b-4519-43e6-8509-d29bc0ba6d43', on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='expectedjoiningdate',
            constraint=models.UniqueConstraint(fields=('designation',), name='unique_designation'),
        ),
    ]
