# Generated by Django 5.2.8 on 2025-12-18 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0013_designation_tat_days_delete_expectedjoiningdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='User responsible for approvals at this level', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
