# Generated by Django 5.2.8 on 2025-12-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0013_workflowtemplate_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='tat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExpectedJoiningDate',
        ),
    ]
