# Generated by Django 5.2.8 on 2025-12-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0014_approvalworkflow_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='interviewer_email_3',
            field=models.EmailField(blank=True, help_text='Optional', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mrf',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
