# Generated by Django 5.2.8 on 2026-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0015_mrf_interviewer_email_3_mrf_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='key_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='required_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='skills_competencies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
