# Generated by Django 5.2.8 on 2026-01-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0016_alter_mrf_key_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='mrf.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='key_responsibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='required_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='salary_range',
            field=models.CharField(blank=True, help_text="e.g., '5-8 LPA'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='skills_competencies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
