# Generated by Django 5.2.8 on 2026-01-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0017_designation_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='code',
        ),
    ]
