# Generated by Django 5.2.8 on 2026-01-27 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0018_remove_designation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='mrf.department'),
        ),
    ]
