# Generated by Django 5.2.8 on 2026-01-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0019_alter_designation_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
