# Generated by Django 5.2.8 on 2026-01-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0020_alter_designation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
