# Generated by Django 5.2.8 on 2026-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0021_designation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='interviewer_email_management_client',
            field=models.EmailField(blank=True, help_text='Interviewer email of management client interview', max_length=50, null=True),
        ),
    ]
