# Generated by Django 5.2.8 on 2026-02-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0023_approvalworkflow_company_department_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='interviewer_email_1',
            field=models.EmailField(blank=True, help_text='Email of HR round interviewer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='interviewer_email_2',
            field=models.EmailField(blank=True, help_text='Email of Technical round interviewer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='interviewer_email_3',
            field=models.EmailField(blank=True, help_text='Email of Case study round interviewer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='interviewer_email_final',
            field=models.EmailField(blank=True, help_text='Email of final round interviewer', max_length=50, null=True),
        ),
    ]
