# Generated by Django 5.2.8 on 2026-02-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0024_alter_mrf_interviewer_email_1_and_more'),
        ('slots', '0010_interviewfeedback_case_study_round_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='case_study_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_study_mrfs', to='slots.interviewer'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='final_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_mrfs', to='slots.interviewer'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='hr_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_mrfs', to='slots.interviewer'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='management_client_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_client_mrfs', to='slots.interviewer'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='technical_interviewers',
            field=models.ManyToManyField(blank=True, related_name='technical_mrfs', to='slots.interviewer'),
        ),
    ]
