# Generated by Django 5.2.8 on 2026-02-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0025_mrf_case_study_interviewer_mrf_final_interviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
