# Generated by Django 5.2.8 on 2026-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0026_mrf_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='expirience',
            field=models.CharField(blank=True, help_text="e.g., '1-3 years'", max_length=100, null=True),
        ),
    ]
