# Generated by Django 5.2.8 on 2026-03-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0027_designation_expirience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrf.department'),
        ),
    ]
