# Generated by Django 5.2.8 on 2026-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0028_workflowtemplate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('pending_level_3', 'Pending Level 3 Approval'), ('on_hold', 'On Hold'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='draft', max_length=30),
        ),
    ]
