# Generated by Django 5.2.8 on 2026-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0029_alter_mrf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='held_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when put on hold', null=True),
        ),
        migrations.AddField(
            model_name='mrf',
            name='hold_reason',
            field=models.TextField(blank=True, help_text='Reason for holding the job'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('pending_level_3', 'Pending Level 3 Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], help_text='Status before being put on hold (for restoration)', max_length=50, null=True),
        ),
    ]
