# Generated by Django 5.2.8 on 2026-03-30 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0030_mrf_held_at_mrf_hold_reason_mrf_previous_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrf_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
