# Generated by Django 5.2.8 on 2026-05-07 10:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0033_alter_approvalworkflow_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, this MRF uses direct approval levels and has restricted visibility'),
        ),
        migrations.AddField(
            model_name='mrf',
            name='selected_viewers',
            field=models.ManyToManyField(blank=True, help_text='Users who can view this private MRF (in addition to creator, approvers, and admin)', related_name='viewable_private_mrfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='The workflow template this MRF follows', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mrfs', to='mrf.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='PrivateMRFApprovalLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(help_text='Approval level (1, 2, 3, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(help_text='User who can approve at this level', on_delete=django.db.models.deletion.PROTECT, related_name='private_mrf_approval_levels', to=settings.AUTH_USER_MODEL)),
                ('mrf', models.ForeignKey(help_text='The private MRF this approval level belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='private_approval_levels', to='mrf.mrf')),
            ],
            options={
                'ordering': ['mrf', 'level'],
                'unique_together': {('mrf', 'level')},
            },
        ),
    ]
