# Generated by Django 5.2.8 on 2026-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0034_mrf_is_private_mrf_selected_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrf',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('pending_level_3', 'Pending Level 3 Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required'), ('joining_pending', 'Joining Pending'), ('filled', 'Position Filled'), ('closed', 'Closed')], help_text='Status before being put on hold (for restoration)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mrf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_level_1', 'Pending Level 1 Approval'), ('pending_level_2', 'Pending Level 2 Approval'), ('pending_level_3', 'Pending Level 3 Approval'), ('on_hold', 'On Hold'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required'), ('joining_pending', 'Joining Pending'), ('filled', 'Position Filled'), ('closed', 'Closed')], default='draft', max_length=30),
        ),
    ]
