# Generated by Django 5.2.8 on 2026-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrf', '0035_alter_mrf_previous_status_alter_mrf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrf',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
