# Generated by Django 5.2.8 on 2025-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_pending', 'Interview Pending'), ('interview_done', 'Interview Completed'), ('interview_rejected', 'Rejected After Interview'), ('selected', 'Selected by Interview Panel'), ('approval_pending', 'Approval Pending (Sent to Hiring Manager)'), ('approved', 'Approved by Hiring Manager'), ('approval_rejected', 'Rejected During Approval'), ('offer_pending', 'Offer Preparation Pending'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected by Candidate'), ('docs_pending', 'Documents Pending'), ('docs_received', 'Documents Received'), ('joining_pending', 'Joining Pending'), ('joined', 'Joined'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
