# Generated by Django 5.2.8 on 2025-12-03 11:02

import django.db.models.deletion
import onboarding.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0011_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=onboarding.models.application_upload_path)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.jobapplication')),
            ],
        ),
    ]
