# Generated by Django 5.2.8 on 2025-11-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_candidate_designation_candidate_expirience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_pending', 'Interview Pending'), ('interview_done', 'Interview Completed'), ('interview_rejected', 'Rejected After Interview'), ('selected', 'Selected by Interview Panel'), ('approval_pending', 'Approval Pending (Sent to Hiring Manager)'), ('approved', 'Approved by Hiring Manager'), ('approval_rejected', 'Rejected During Approval'), ('offer_pending', 'Offer Preparation Pending'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected by Candidate'), ('docs_pending', 'Documents Pending'), ('docs_received', 'Documents Received'), ('joining_pending', 'Joining Pending'), ('joined', 'Joined'), ('rejected', 'Rejected')], default='applied', max_length=50),
        ),
    ]
