# Generated by Django 5.2.8 on 2026-02-10 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_jobapplication_status'),
        ('onboarding', '0002_approvalnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAnnexure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('effective_from', models.DateField()),
                ('gross_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ctc_annual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_annexure', to='jobs.jobapplication')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_annexures', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_annexures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAnnexureHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent for Approval'), ('revised', 'Revised'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('snapshot', models.JSONField(help_text='Snapshot of salary annexure at the time of action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annexure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='onboarding.salaryannexure')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('employer_contribution', 'Employer Contribution'), ('employee_contribution', 'Employee Contribution')], max_length=30)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_statutory', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('annexure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='onboarding.salaryannexure')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
