# Generated by Django 5.2.8 on 2025-11-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_candidate_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_pending', 'Interview Pending'), ('interview_done', 'Interview Completed'), ('interview_rejected', 'Rejected After Interview'), ('selected', 'Selected by Interview Panel'), ('approval_pending', 'Approval Pending (Sent to Hiring Manager)'), ('approved', 'Approved by Hiring Manager'), ('approval_rejected', 'Rejected During Approval'), ('salary_docs_pending', 'Salary Documents Pending'), ('salary_docs_uploaded', 'Salary Documents Uploaded'), ('hr_review_docs', 'HR Reviewing Salary Documents'), ('hr_review_ok', 'HR Review Completed'), ('hr_review_rejected', 'HR Rejected Salary Documents'), ('salary_annexure_prep', 'Salary Annexure Under Preparation'), ('salary_annexure_sent', 'Salary Annexure Sent to HR Head'), ('approved_annexure', 'Salary Annexure Approved'), ('rejected_annexure', 'Salary Annexure Rejected'), ('offer_pending', 'Offer Preparation Pending'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected by Candidate'), ('resignation_pending', 'Resignation Pending (Upload Required)'), ('resignation_uploaded', 'Resignation Uploaded'), ('resignation_review', 'Resignation Under Review'), ('resignation_approved', 'Resignation Approved'), ('resignation_rejected', 'Resignation Rejected'), ('docs_pending', 'Joining Documents Pending'), ('docs_uploaded', 'Joining Documents Uploaded'), ('review_docs', 'Document Review In Progress'), ('docs_approved', 'Documents Approved'), ('docs_incomplete', 'Documents Incomplete'), ('docs_unclear', 'Documents Unclear'), ('joining_pending', 'Joining Pending'), ('joining_poned', 'Joining Postponed'), ('joined', 'Joined'), ('rejected', 'Rejected')], default='applied', max_length=50),
        ),
    ]
