# Generated by Django 5.2.8 on 2026-02-10 11:11

import django.db.models.deletion
import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_alter_jobapplication_status'),
        ('onboarding', '0003_salaryannexure_salaryannexurehistory_salarycomponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicationdocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='education_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='education_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_letter_1',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_letter_2',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='personal_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='personal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='photograph',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='post_graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='relieving_letter',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_acceptance',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_letter',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_1',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_2',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_3',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='tenth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='twelfth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='job_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.jobapplication'),
        ),
    ]
