# Generated by Django 5.2.8 on 2026-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_rename_uploaded_at_jobapplicationdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='education_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('incomplete', 'Incomplete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='experience_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('incomplete', 'Incomplete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='personal_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('incomplete', 'Incomplete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='resignation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('incomplete', 'Incomplete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplicationdocument',
            name='salary_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('approved', 'Approved'), ('unclear', 'Unclear'), ('incomplete', 'Incomplete'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
