# Generated by Django 5.2.8 on 2026-02-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_jobapplicationdocument_education_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicationdocument',
            old_name='education_remarks',
            new_name='joining_docs_remarks',
        ),
        migrations.RenameField(
            model_name='jobapplicationdocument',
            old_name='education_status',
            new_name='joining_docs_status',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='experience_remarks',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='experience_status',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='personal_remarks',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='personal_status',
        ),
    ]
