# Generated by Django 5.2.8 on 2026-02-16 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_jobapplication_status'),
        ('onboarding', '0009_alter_approvalnote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoho_request_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='signed_docs/')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'offer_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
