# Generated by Django 5.2.8 on 2026-02-17 10:32

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_offerdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='resignation_remarks',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='resignation_status',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='salary_remarks',
        ),
        migrations.RemoveField(
            model_name='jobapplicationdocument',
            name='salary_status',
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_1',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_2',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_3',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='increment_letter',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='offer_letter_1',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='offer_letter_2',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
    ]
