# Generated by Django 5.2.8 on 2026-02-17 10:54

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_remove_jobapplicationdocument_resignation_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='created_offer_letter',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
    ]
