# Generated by Django 5.2.8 on 2026-02-21 11:40

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_alter_approvalnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_annexure',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.application_upload_path),
        ),
    ]
