# Generated by Django 5.2.8 on 2026-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_jobapplicationdocument_salary_annexure'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='aadhaar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='address_proof_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='bank_statement_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='created_offer_letter_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_letter_1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='experience_letter_2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='increment_letter_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='offer_letter_1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='offer_letter_2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='pan_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='passport_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='photograph_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='relieving_letter_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_acceptance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='resignation_letter_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_annexure_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='salary_slip_3_approved',
            field=models.BooleanField(default=False),
        ),
    ]
