# Generated by Django 5.2.8 on 2026-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_jobapplicationdocument_aadhaar_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_1_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_2_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='additional_certificate_3_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='graduation_certificate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='post_graduation_certificate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='tenth_certificate_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='twelfth_certificate_approved',
            field=models.BooleanField(default=False),
        ),
    ]
