# Generated by Django 5.2.8 on 2026-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_jobapplicationdocument_additional_certificate_1_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='reupload_docuemnts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
