# Generated by Django 5.2.8 on 2026-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_alter_approvalnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='reupload_docuemnts_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
