# Generated by Django 5.2.8 on 2026-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_jobapplicationdocument_reupload_docuemnts_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
