# Generated by Django 5.2.8 on 2026-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_approvalnote_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalnote',
            name='approved_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalnote',
            name='rejected_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
