# Generated by Django 5.2.8 on 2026-04-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_application_rejected_by'),
        ('onboarding', '0023_approvalnote_approved_at_approvalnote_rejected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('signed', 'Signed'), ('declined', 'Declined'), ('voided', 'Voided'), ('error', 'Error')], default='pending', max_length=20)),
                ('signer_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('signed_url', models.URLField(blank=True, null=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docusign_offer', to='jobs.jobapplication')),
            ],
        ),
    ]
