# Generated by Django 5.2.8 on 2026-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_docusignoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdocument',
            name='zoho_request_id',
        ),
        migrations.AddField(
            model_name='offerdocument',
            name='zoho_document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
