# Generated by Django 5.2.8 on 2026-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0026_alter_approvalnote_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='annexure_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='annexure_rejection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='annexure_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicationdocument',
            name='document_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
