# Generated by Django 5.2.8 on 2026-07-06 05:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_application_is_active_referralapplication_is_active_and_more'),
        ('onboarding', '0030_alter_approvalnote_bgv_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text='Primary recipient email address', max_length=254)),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='List of CC email addresses')),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body content')),
                ('event', models.CharField(help_text='The event/stage that triggered this email (e.g., joined, shortlisted)', max_length=100)),
                ('email_type', models.CharField(choices=[('candidate', 'Candidate Notification'), ('internal', 'Internal Notification'), ('approval', 'Approval Request'), ('offer', 'Offer Letter'), ('feedback', 'Feedback Reminder'), ('assignment', 'Job Assignment'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(blank=True, help_text='Linked candidate application, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient_email'], name='email_logs_recipie_00ae8d_idx'), models.Index(fields=['event'], name='email_logs_event_ff33ab_idx'), models.Index(fields=['sent_at'], name='email_logs_sent_at_9fc48d_idx'), models.Index(fields=['candidate'], name='email_logs_candida_deee90_idx')],
            },
        ),
    ]
