# Generated by Django 5.2.8 on 2026-07-25 04:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0079_jobapplication_is_hod_survey_filled'),
        ('onboarding', '0031_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('assets', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_category', models.CharField(blank=True, max_length=100, null=True)),
                ('center_office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_for_collecting_assets', models.CharField(blank=True, max_length=100, null=True)),
                ('team_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('work_from', models.CharField(blank=True, max_length=100, null=True)),
                ('crafter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('emails_to_notify', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_form', to='jobs.jobapplication')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_onboarding_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_type', models.CharField(choices=[('candidate', 'Candidate Satisfaction Survey'), ('hod', 'HOD Satisfaction Survey')], max_length=20)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('responses', models.JSONField(default=dict, help_text="JSON dict of question-answer pairs, e.g. {'overall_rating': 4, 'comments': '...'}")),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-submitted_at'],
                'unique_together': {('job_application', 'survey_type')},
            },
        ),
    ]
