# Generated by Django 5.2.8 on 2026-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0032_onboardingform_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_type',
            field=models.CharField(choices=[('candidate', '30-Day Candidate Satisfaction Survey'), ('hod', '30-Day HOD Satisfaction Survey'), ('90_day_candidate', '90-Day Candidate Survey')], max_length=20),
        ),
    ]
