# Generated by Django 5.2.8 on 2026-08-05 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0082_d90_candidate_survey_only'),
        ('onboarding', '0033_d90_candidate_survey_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('d45', 'Day 45 Check-in'), ('d90', 'Day 90 Final Review')], max_length=10)),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=512, null=True)),
                ('meeting_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_calls', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'onboarding_calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
