# Generated by Django 5.2.8 on 2026-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0034_add_onboarding_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey_type',
            field=models.CharField(choices=[('30_day_candidate', '30-Day Candidate Satisfaction Survey'), ('hod', '30-Day HOD Satisfaction Survey'), ('90_day_candidate', '90-Day Candidate Survey')], max_length=20),
        ),
    ]
