# Generated by Django 5.2.8 on 2026-08-11 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0084_alter_jobapplication_status'),
        ('onboarding', '0037_alter_approvalnote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEsignTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('SA', 'Service Agreement'), ('NDA', 'NDA'), ('BOND', 'Employment Bond'), ('ISMS_1', 'ISMS Policy Part 1'), ('ISMS_2', 'ISMS Policy Part 2'), ('FORM_2', 'Form 2'), ('NOMINATION_INS', 'Nomination-Insurance Form'), ('KRA', 'KRA (Key Result Areas)'), ('FORM_F', 'Form F'), ('FORM_11', 'Form 11'), ('IT_ASSET', 'IT Asset Handover / Digital Asset Confirmation')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending — File Not Yet Uploaded'), ('ready', 'File Uploaded, Not Yet Sent'), ('sent', 'Sent to Zoho Sign'), ('viewed', 'Viewed by Candidate'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('reminded', 'Reminder Sent')], default='pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='onboarding/esign_source/')),
                ('zoho_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zoho_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esign_documents', to='jobs.jobapplication')),
            ],
            options={
                'db_table': 'onboarding_document_esign_tasks',
                'ordering': ['-created_at'],
                'unique_together': {('job_application', 'doc_type')},
            },
        ),
    ]
