# Generated by Django 5.2.8 on 2026-08-18 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0038_documentesigntask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_type', models.CharField(help_text='e.g. 30_day_candidate, hod_junior, hod_senior, 90_day_candidate', max_length=50, unique=True)),
                ('structure', models.JSONField(default=dict, help_text='JSON representation of the survey structure (title, sections, questions, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'survey_structures',
            },
        ),
    ]
