# Generated by Django 5.2.8 on 2026-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0040_add_terminated_status_to_approvalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentesigntask',
            name='doc_type',
            field=models.CharField(choices=[('SA', 'Service Agreement'), ('NDA', 'NDA'), ('BOND', 'Employment Bond'), ('ISMS_1', 'ISMS Policy Part 1'), ('ISMS_2', 'ISMS Policy Part 2'), ('FORM_2', 'Form 2'), ('NOMINATION_INS', 'Nomination-Insurance Form'), ('KRA', 'KRA (Key Result Areas)'), ('FORM_F', 'Form F'), ('FORM_11', 'Form 11'), ('IT_ASSET', 'IT Asset Handover / Digital Asset Confirmation'), ('UNDERTAKING', 'Undertaking Sign-off Document')], max_length=20),
        ),
    ]
