# Generated by Django 5.2.8 on 2026-06-05 05:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, help_text="Registry key, e.g. 'interview_feedback_reminder'", max_length=100)),
                ('task_kwargs', models.JSONField(blank=True, default=dict, help_text='Serialisable keyword arguments passed to the task function')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When the task should next execute')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True the task auto-reschedules after completion')),
                ('interval_seconds', models.IntegerField(blank=True, help_text='Seconds between recurring executions', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='idx_sched_status_at')],
            },
        ),
    ]
